In [9]:
import csv
import requests
from bs4 import BeautifulSoup

# The base URL of the webpage to scrape
base_url = 'https://phishtank.org/phish_detail.php?phish_id={}'

# Open a CSV file for writing
with open('table_values_invalid.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['ID', 'Phish URL', 'Submitted', 'Valid?', 'Online?'])

    for page_num in range(0, 3000): 
        url = base_url.format(page_num)

        # Send a GET request to the URL
        response = requests.get(url)

        # Create a BeautifulSoup object to parse the HTML content of the response
        soup = BeautifulSoup(response.content, 'html.parser')

        # Find the table element containing the desired rows
        table = soup.find('table', class_='data')

        # Find all the rows in the table
        rows = table.find_all('tr')

        # Extract the values from each row and add them to a list of lists
        table_values = []
        for row in rows:
            row_values = [cell.text.strip() for cell in row.find_all('td', class_='value')]
            if row_values:
                table_values.append(row_values)

        # Write the table values to the CSV file, with each row in a separate row
        writer.writerows(table_values)

AttributeError: ignored

In [2]:
import pandas as pd
data = pd.read_csv("/content/table_values_valid (3).csv")

In [3]:
data

,ID,Phish URL,Submitted,Valid?,Online?
0,8089333,https://baleecixhy.duckdns.org/added on Mar 24...,by shinya,VALID PHISH,Offline
1,8089330,https://tinyurl.com/bddp7mheadded on Mar 24th ...,by D3Lab,VALID PHISH,ONLINE
2,8089329,https://mps.service-sys-2fa.com/added on Mar 2...,by D3Lab,VALID PHISH,ONLINE
3,8089314,https://xyzpblcoar.duckdns.org/added on Mar 24...,by shinya,VALID PHISH,ONLINE
4,8089297,https://tthkkrhuyq.duckdns.org/added on Mar 24...,by shinya,VALID PHISH,ONLINE
...,...,...,...,...,...
184475,7829903,http://www.aseeeaon.accseeccrsoe.vsddjm.top/pa...,by Micha,VALID PHISH,Offline
184476,7829902,http://www.aseeeaon.accseeccrsoe.vtcujb.top/pa...,by Micha,VALID PHISH,Offline
184477,7829901,http://www.aseeeaon.accseeccrsoe.vxhxkw.top/pa...,by Micha,VALID PHISH,Offline
184478,7829900,http://www.aseeeaon.accseeccrsoe.wbintx.top/pa...,by Micha,VALID PHISH,Offline
184479,7829899,http://www.aseeeaon.accseeccrsoe.wblxdw.top/pa...,by Micha,VALID PHISH,Offline

In [10]:
arr = data['ID'].values

In [11]:
arr

array([8089333, 8089330, 8089329, ..., 7829901, 7829900, 7829899])

In [ ]:
import csv
import requests
from bs4 import BeautifulSoup
import time
# The base URL of the webpage to scrape
base_url = 'https://phishtank.org/phish_detail.php?phish_id={}'

# Open a CSV file for writing
with open('whitelist.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['ID', 'Phish URL'])
    g=1
    for i in arr: 
        g=g+1
        url = base_url.format(i)
        # Send a GET request to the URL
        response = requests.get(url)

        # Create a BeautifulSoup object to parse the HTML content of the response
        soup = BeautifulSoup(response.content, 'html.parser')
        
        span_tag = soup.find('span', attrs={'style': 'word-wrap:break-word;'}).find('b')
        value = span_tag.text
        if(g%15==0):
            time.sleep(5)
        # Extract the values from each row and add them to a list of lists
        table_values = [[i,value]]
        # Write the table values to the CSV file, with each row in a separate row
        writer.writerows(table_values)